const ActionType = {
    CHANGE_POPUP: 'CHANGE_POPUP', 
    CHANGE_ISLOGIN: 'CHANGE_ISLOGIN', 
    CHANGE_LOADING: 'CHANGE_LOADING',
    UPDATE_USER: 'UPDATE_USER',
    SET_NOTES: 'SET_NOTES',
}

export default ActionType;